[package]
name = "check_sr25519"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.2.1"
borsh = "1.5.7"
schnorrkel = { git = "https://github.com/mrkobold/schnorrkel" }
